#Crear el conjunto
listas = set()
listas.add("Lamborghini")
listas.add("Ferrari")
listas.add("Mclaren")
listas.add("Audi")
listas.add("Aston Martin")
listas.add("Vuhl")
listas.add("Maserati")
print (listas)
listas.update(["Lotus", "Rolls Royce", "Bentley"])
print (listas)
listas.remove('Ferrari')
print (listas)